spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/quesra
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  # application.yml

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: openquesra@gmail.com
    password: thsyjrzbaprgyoxu
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
    port: 8000

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

